japanese_parties = ['自由民主党', '立憲民主党', '日本維新の会', '公明党', 
                    '国民民主党', '日本共産党', 'れいわ新撰組', '参政党',
       '日本保守党', '社会民主党', '無所属連合', 'チームみらい', '日本誠心会', 
       '日本改革党', '再生の道', 'NHK党', '幸福実現党', 'ごぼうの党', '日本第一党',
       '新党くにもり', '維新政党・新風']
english_parties = ['Liberal Democratic Party', 'Constitutional Democratic Party', 'Japan Innovation Party', 'Komeito', 
                   'Democratic Party For the People', 'Japanese Communist Party', 'Reiwa Shinsengumi', 
                   'Sanseito', 'Conservative Party of Japan', 'Social Democratic Party', 
                   'Independent Alliance', 'Team Mirai', 'Nippon Seishinkai', 'Nihon Kakumeito', 
                   'Saisei no Michi', 'NHK Party', 'The Happiness Realization Party', 'Gobonoto', 'Japan First Party',
                    'Shinto Kunimori', 'Ishin Party Shimpu' ]
abbreviations = ['LDP', 'CDP', 'JIP', 'NKP', 'DPP', 'JCP', 'REIWA', 'DIY', 'CPJ', 'SDP', 'IND', 
                 'MIRAI', 'NSK', 'NKT', 'SAISEI', 'NHK', 'HRP', 'GBT', 'JFP', 'STK', 'IPS']
english_prefectures = ['Hokkaido', 'Aomori', 'Iwate', 'Miyagi', 'Akita', 'Yamagata', 'Fukushima', 'Ibaraki',
                       'Tochigi', 'Gunma', 'Saitama', 'Chiba', 'Tokyo', 'Kanagawa', 'Niigata',
                       'Toyama', 'Ishikawa', 'Fukui', 'Yamanashi', 'Nagano', 'Gifu', 'Shizuoka', 'Aichi',
                       'Mie', 'Shiga', 'Kyoto', 'Osaka', 'Hyogo', 'Nara', 'Wakayama', 'Tottori', 'Shimane', 'Okayama',
                       'Hiroshima', 'Yamaguchi', 'Tokushima', 'Kagawa', 'Ehime', 'Kochi', 'Fukuoka', 
                       'Saga', 'Nagasaki', 'Kumamoto', 'Oita', 'Miyazaki', 'Kagoshima', 'Okinawa']
japanese_prefectures = ['北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県', '茨城県', '栃木県', '群馬県',
       '埼玉県', '千葉県', '東京都', '神奈川県', '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県',
       '岐阜県', '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県',
       '鳥取県', '島根県', '岡山県', '広島県', '山口県', '徳島県', '香川県', '愛媛県', '高知県', '福岡県',
       '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県']

jp_party_to_eng = {'自由民主党': 'Liberal Democratic Party',
 '立憲民主党': 'Constitutional Democratic Party',
 '日本維新の会': 'Japan Innovation Party',
 '公明党': 'Komeito',
 '国民民主党': 'Democratic Party For the People',
 '日本共産党': 'Japanese Communist Party',
 'れいわ新選組': 'Reiwa Shinsengumi',
 '参政党': 'Sanseito',
 '日本保守党': 'Conservative Party of Japan',
 '社会民主党': 'Social Democratic Party',
 '無所属連合': 'Independent Alliance',
 'チームみらい': 'Team Mirai',
 '日本誠心会': 'Nippon Seishinkai',
 '日本改革党': 'Nihon Kakumeito',
 '再生の道': 'Saisei no Michi',
 'NHK党': 'NHK Party',
 '幸福実現党': 'The Happiness Realization Party',
 'ごぼうの党': 'Gobonoto',
 '日本第一党': 'Japan First Party',
 '新党くにもり': 'Shinto Kunimori',
 '維新政党・新風': 'Ishin Party Shimpu',
 'みんなでつくる党': 'Minna De Tsukuru Party',
 '安楽死制度を考える会': 'Euthanasia Consideration Party',
 '中道改革連合': 'Centrist Reform Alliance',
 '減税日本・ゆうこく連合': 'Tax Cuts Japan and Yukoku Alliance'}

jp_party_to_abbrv = {'自由民主党': 'LDP',
 '立憲民主党': 'CDP',
 '日本維新の会': 'JIP',
 '公明党': 'NKP',
 '国民民主党': 'DPP',
 '日本共産党': 'JCP',
 'れいわ新撰組': 'REIWA',
 '参政党': 'DIY',
 '日本保守党': 'CPJ',
 '社会民主党': 'SDP',
 '無所属連合': 'IND',
 'チームみらい': 'MIRAI',
 '日本誠心会': 'NSK',
 '日本改革党': 'NKT',
 '再生の道': 'SAISEI',
 'NHK党': 'NHK',
 '幸福実現党': 'HRP',
 'ごぼうの党': 'GBT',
 '日本第一党': 'JFP',
 '新党くにもり': 'STK',
 '維新政党・新風': 'IPS',
 'みんなでつくる党': 'MTP',
 '安楽死制度を考える会': 'ANRAKU',
 '中道改革連合': 'CRA',
 '減税日本・ゆうこく連合': 'TAXCUT'}

eng_party_to_jp = {'Liberal Democratic Party': '自由民主党',
 'Constitutional Democratic Party': '立憲民主党',
 'Japan Innovation Party': '日本維新の会',
 'Komeito': '公明党',
 'Democratic Party For the People': '国民民主党',
 'Japanese Communist Party': '日本共産党',
 'Reiwa Shinsengumi': 'れいわ新撰組',
 'Sanseito': '参政党',
 'Conservative Party of Japan': '日本保守党',
 'Social Democratic Party': '社会民主党',
 'Independent Alliance': '無所属連合',
 'Team Mirai': 'チームみらい',
 'Nippon Seishinkai': '日本誠心会',
 'Nihon Kakumeito': '日本改革党',
 'Saisei no Michi': '再生の道',
 'NHK Party': 'NHK党',
 'The Happiness Realization Party': '幸福実現党',
 'Gobonoto': 'ごぼうの党',
 'Japan First Party': '日本第一党',
 'Shinto Kunimori': '新党くにもり',
 'Ishin Party Shimpu': '維新政党・新風',
 'Minna De Tsukuru Party':'みんなでつくる党',
 'Euthanasia Consideration Party': '安楽死制度を考える会',
 'Centrist Reform Alliance': '中道改革連合',
 'Tax Cuts Japan and Yukoku Alliance':'減税日本・ゆうこく連合'}

eng_party_to_abbrv = {'Liberal Democratic Party': 'LDP',
 'Constitutional Democratic Party': 'CDP',
 'Japan Innovation Party': 'JIP',
 'Komeito': 'NKP',
 'Democratic Party For the People': 'DPP',
 'Japanese Communist Party': 'JCP',
 'Reiwa Shinsengumi': 'REIWA',
 'Sanseito': 'DIY',
 'Conservative Party of Japan': 'CPJ',
 'Social Democratic Party': 'SDP',
 'Independent Alliance': 'IND',
 'Team Mirai': 'MIRAI',
 'Nippon Seishinkai': 'NSK',
 'Nihon Kakumeito': 'NKT',
 'Saisei no Michi': 'SAISEI',
 'NHK Party': 'NHK',
 'The Happiness Realization Party': 'HRP',
 'Gobonoto': 'GBT',
 'Japan First Party': 'JFP',
 'Shinto Kunimori': 'STK',
 'Ishin Party Shimpu': 'IPS',
 'Minna De Tsukuru Party': 'MTP',
 'Euthanasia Consideration Party': 'ANRAKU',
 'Centrist Reform Alliance': 'CRA',
 'Tax Cuts Japan and Yukoku Alliance': 'TAXCUT'}

jp_prefect_to_eng = {'北海道': 'Hokkaido',
 '青森県': 'Aomori',
 '岩手県': 'Iwate',
 '宮城県': 'Miyagi',
 '秋田県': 'Akita',
 '山形県': 'Yamagata',
 '福島県': 'Fukushima',
 '茨城県': 'Ibaraki',
 '栃木県': 'Tochigi',
 '群馬県': 'Gunma',
 '埼玉県': 'Saitama',
 '千葉県': 'Chiba',
 '東京都': 'Tokyo',
 '神奈川県': 'Kanagawa',
 '新潟県': 'Niigata',
 '富山県': 'Toyama',
 '石川県': 'Ishikawa',
 '福井県': 'Fukui',
 '山梨県': 'Yamanashi',
 '長野県': 'Nagano',
 '岐阜県': 'Gifu',
 '静岡県': 'Shizuoka',
 '愛知県': 'Aichi',
 '三重県': 'Mie',
 '滋賀県': 'Shiga',
 '京都府': 'Kyoto',
 '大阪府': 'Osaka',
 '兵庫県': 'Hyogo',
 '奈良県': 'Nara',
 '和歌山県': 'Wakayama',
 '鳥取県': 'Tottori',
 '島根県': 'Shimane',
 '岡山県': 'Okayama',
 '広島県': 'Hiroshima',
 '山口県': 'Yamaguchi',
 '徳島県': 'Tokushima',
 '香川県': 'Kagawa',
 '愛媛県': 'Ehime',
 '高知県': 'Kochi',
 '福岡県': 'Fukuoka',
 '佐賀県': 'Saga',
 '長崎県': 'Nagasaki',
 '熊本県': 'Kumamoto',
 '大分県': 'Oita',
 '宮崎県': 'Miyazaki',
 '鹿児島県': 'Kagoshima',
 '沖縄県': 'Okinawa'}

eng_prefect_to_jp = {'Hokkaido': '北海道',
 'Aomori': '青森県',
 'Iwate': '岩手県',
 'Miyagi': '宮城県',
 'Akita': '秋田県',
 'Yamagata': '山形県',
 'Fukushima': '福島県',
 'Ibaraki': '茨城県',
 'Tochigi': '栃木県',
 'Gunma': '群馬県',
 'Saitama': '埼玉県',
 'Chiba': '千葉県',
 'Tokyo': '東京都',
 'Kanagawa': '神奈川県',
 'Niigata': '新潟県',
 'Toyama': '富山県',
 'Ishikawa': '石川県',
 'Fukui': '福井県',
 'Yamanashi': '山梨県',
 'Nagano': '長野県',
 'Gifu': '岐阜県',
 'Shizuoka': '静岡県',
 'Aichi': '愛知県',
 'Mie': '三重県',
 'Shiga': '滋賀県',
 'Kyoto': '京都府',
 'Osaka': '大阪府',
 'Hyogo': '兵庫県',
 'Nara': '奈良県',
 'Wakayama': '和歌山県',
 'Tottori': '鳥取県',
 'Shimane': '島根県',
 'Okayama': '岡山県',
 'Hiroshima': '広島県',
 'Yamaguchi': '山口県',
 'Tokushima': '徳島県',
 'Kagawa': '香川県',
 'Ehime': '愛媛県',
 'Kochi': '高知県',
 'Fukuoka': '福岡県',
 'Saga': '佐賀県',
 'Nagasaki': '長崎県',
 'Kumamoto': '熊本県',
 'Oita': '大分県',
 'Miyazaki': '宮崎県',
 'Kagoshima': '鹿児島県',
 'Okinawa': '沖縄県'}